#!/usr/bin/env python3
"""Update ULTRA_APP_ORIGIN in backend/.env (and frontend/.env.local) for tunnel mode."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV = ROOT / "backend" / ".env"
ENV_LOCAL = ROOT / "frontend" / ".env.local"
TUNNEL_FILE = ROOT / ".tunnel-url"


def set_key(text: str, key: str, val: str) -> str:
    pattern = rf"^{re.escape(key)}=.*$"
    line = f"{key}={val}"
    if re.search(pattern, text, re.M):
        return re.sub(pattern, line, text, count=1, flags=re.M)
    if text and not text.endswith("\n"):
        text += "\n"
    return text + line + "\n"


def main() -> None:
    if len(sys.argv) < 2:
        print("usage: set_tunnel_origin.py https://xxx.trycloudflare.com", file=sys.stderr)
        sys.exit(2)
    origin = sys.argv[1].rstrip("/")
    if not origin.startswith("https://"):
        print("origin must be https://", file=sys.stderr)
        sys.exit(2)

    if ENV.exists():
        text = ENV.read_text(encoding="utf-8")
    else:
        text = "# Ultra env\n"
    text = set_key(text, "ULTRA_APP_ORIGIN", origin)
    text = set_key(text, "GOOGLE_REDIRECT_URI", f"{origin}/api/auth/google/callback")
    text = set_key(text, "STRAVA_REDIRECT_URI", f"{origin}/api/providers/strava/callback")
    ENV.write_text(text, encoding="utf-8")

    ENV_LOCAL.write_text(
        f"# Auto-generated by setup.sh — Cloudflare Tunnel\n"
        f"VITE_PUBLIC_URL={origin}\n"
        f"VITE_TUNNEL_URL={origin}\n",
        encoding="utf-8",
    )
    TUNNEL_FILE.write_text(origin + "\n", encoding="utf-8")
    print(origin)


if __name__ == "__main__":
    main()
